### PR TITLE
Add labels to "end type" statements to eliminate warnings in CCPP pre…

### PR DESCRIPTION
**Pull request by mkavulich**
This PR adds labels for "end type" statements in the rrtmgp code. These end statements are technically not required by the CCPP standards, but all other "end" statements in CCPP must be labeled, and this helps reduce the potential for ambiguity in the code. These changes will also eliminate warnings when running ccpp_prebuild.py and the new ccpp_track_variables.py script (https://github.com/NCAR/ccpp-framework/pull/419):

```
WARNING:root:In file mo_gas_optics_rrtmgp.F90, module mo_gas_optics_rrtmgp
WARNING:root:Encountered closing statement "end type" without type name; assume type_name is ty_gas_optics_rrtmgp
WARNING:root:In file mo_optical_props.F90, module mo_optical_props
WARNING:root:Encountered closing statement "end type" without type name; assume type_name is ty_optical_props
WARNING:root:In file mo_optical_props.F90, module mo_optical_props
```

etc.

This should have no change in results, as it is simply for human (and CCPP) readability.

### CODE REVIEW

**Comment by RobertPincus** [comment]
Hi, thanks for this contribution @mkavulich. I don't mind doing this - could you please change the target of the PR to `develop`? The changes will make their way downstream to `dtc/ccpp` eventually.

**Comment by mkavulich** [comment]
@RobertPincus Sure, I originally had targeted there but I didn't realize the branches had diverged so much, so my PR (based on the dtc/ccpp branch) was bringing in a lot of unrelated changes to develop. I can re-open this PR based on the develop branch.

**Comment by RobertPincus** [comment]
@mkavulich Aha. Mayne don't bother then - the changes are small enough that I can introduce them by hand.

**Comment by dustinswales** [comment]
@mkavulich 
You can close this.
Robert made this change in develop, which I will pull into dtc/ccpp and update the ccpp-physics hash

**Comment by mkavulich** [comment]
@dustinswales Sounds good, thanks for looking into it!

**Pull request closed without merging**
