### PR TITLE
Feature: GPU support via OpenMP 4.5

### PR DESCRIPTION
**Pull request by RobertPincus**
Introduce GPU support via OpenMP 4.5. Work done by Nichols Romero of Argonne National Lab (@naromero77). Continuous integration is pending.

### CODE REVIEW

**Review by alexeedm — APPROVED** [review]
I went through the OpenMP code. It seems that for the most part there is just verbatim translation from OpenACC to OpenMP, with some tmp pointers and loops instead of kernels.
I didn't find any unexpected pragma or any actual significant difference of any kind.
Granted I didn't run the code and I didn't dig into all the pragmas...

All in all, I think if the tests pass this PR is good to merge.

**Comment by naromero77** [comment]
@alexeedm Thanks for your review and your comments. I do want to get this working with Fortran OpenMP GPU compilers from all the major vendors: Intel + NVidia next, AMD later. Would you be able to assist on the NVidia end?

**Comment by alexeedm** [comment]
@naromero77 Sure. OpenMP GPU support is still beta though in NV HPC, so I'll keep in touch with our compiler people to get this working as soon as possible

**Comment by naromero77** [comment]
@alexeedm Thanks. I am at Argonne and need to make the Intel GPU and Intel compilers a high priority (for obvious reason). I also plan to look at Fortran OpenMP for GPU as implemented in GCC, once 11.0 is released.

**Comment by naromero77** [comment]
A couple of acknowledgments for the record. 

@naromero77 This research was supported by the Exascale Computing Project (17-SC-20-SC), a collaborative effort of two U.S. Department of Energy organizations (Office of Science and the National Nuclear Security Administration) responsible for the planning and preparation of a capable exascale ecosystem, including software, applications, hardware, advanced system engineering, and early testbed platforms, in support of the nation’s exascale computing imperative.

@twhite-cray This work was undertaken in collaboration with Dr. Trey White (Cray/HPE) and supported by the Frontier Center of Excellence at Oak Ridge National Laboratory.

**Pull request merged**
