### PR TITLE
All-sky example useful for timing

### PR DESCRIPTION
**Pull request by RobertPincus**
Revises the all-sky example to be useful for timing benchmarks. The atmospheric profile more-or-less follows the profile for RCEMIP at a surface temperature of 300 K. Users specify the number of columns and layers and may choose more than a single iteration. (Array checks are turned off for all but the first iteration). A k-distribution must be specified. Clouds are optional, and occupy 2/3 of columns; aerosols in every other column are optional but require clouds. 

A netCDF file is produced; small files of {LW,SW}x{clouds, clouds+aerosols} are used for verification during continuous integration. Timing output is simple, i.e. 
``` 
ncol   nlay   ngpt  clouds aerosols time_per_col_ms nloops time_total_s time_min_s
     2     32    128       0        0           0.978     24        0.047      0.047
```

Addresses #128

### CODE REVIEW

**Comment by RobertPincus** [comment]
Also: removes use of NCHOME environment variable, removes (optional) use of GPTL timing library in RFMIP examples.

**Comment by Chiil** [comment]
Design is great, tools works well. Compile and test sequence fails on my workstation because files are not adequately copied to reference in allsky test:
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/chiel/devel/rte-rrtmgp/rrtmgp-data/examples/all-sky/reference/rrtmgp-allsky-lw-no-aerosols.nc'
make[1]: *** [Makefile:61: check] Error 1
make[1]: Leaving directory '/home/chiel/devel/rte-rrtmgp/examples/all-sky'
```

I only have a `rrtmgp-allsky-no-aerosols.nc`

**Comment by RobertPincus** [comment]
@Chiil Thanks for the feedback. Did you check out branch `feature-timing` of the data repo as well?

**Comment by Chiil** [comment]
I use the default branch of the data, I merged the test into my cuda branch.On 2 Jul 2023, at 01:37, Robert Pincus ***@***.***> wrote:﻿
@Chiil Thanks for the feedback. Did you check out branch feature-timing of the data repo as well?

**Comment by RobertPincus** [comment]
@Chiil If you check out the `feature-timing` branch of the data repo, do you find all the data there that enables you to run the tests?

**Review by Chiil — APPROVED** [review]
RFMIP and all-sky test pass, flexible configurations work. Code can be merged to develop.

**Pull request merged**
