### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by m214089**
Hi Robert,
this is the pull request for the gas optics problem mentioned in #214 . Hope I did things correct!
Cheerio,
Luis

### CODE REVIEW

**Comment by m214089** [comment]
I explained the change in a comment in the code as the the programming style is not followed, hopefully preventing changes back.

**Comment by m214089** [comment]
Hmmm, CI is strange: ifx - internal compiler error, cce-gpu-xxx -data missing or incorrect read. All this is nothing where I have any control over and for sure not related to my changes ...

**Comment by RobertPincus** [comment]
@m214089 The CI failures are "expected" - the OpenMP GPU offload implementation has never worked on either Cray CCE nor Intel IFX.

**Review by RobertPincus — APPROVED** [review]
Thanks for this fix.

**Pull request merged**
