### PR TITLE
CCPP metadata updates and bug fixes

### PR DESCRIPTION
**Pull request by climbfuji**
A few updates and bug fixes to the CCPP metadata and the metadata hooks in the Fortran code, required for consistency and a future update of the ccpp-framework.

Also: convert `rte/mo_optical_props.F90` from dos line endings to unix line endings (no code changes).

Associated PRs:

https://github.com/NCAR/ccpp-framework/pull/391
https://github.com/earth-system-radiation/rte-rrtmgp/pull/133
https://github.com/NCAR/ccpp-physics/pull/718
https://github.com/NOAA-EMC/fv3atm/pull/367
https://github.com/ufs-community/ufs-weather-model/pull/745

For regression testing, see https://github.com/ufs-community/ufs-weather-model/pull/745.

### CODE REVIEW

**Review by dustinswales — COMMENTED** [review]
This all seems fine, except the change rte/mo_optical_props.F90. The changes should be isolated to the new "htmlinclude" for ty_optical_props_1scl/2str/nstr ccpp table properties.

**Comment by climbfuji** [comment]
> This all seems fine, except the change rte/mo_optical_props.F90. The changes should be isolated to the new "htmlinclude" for ty_optical_props_1scl/2str/nstr ccpp table properties.

Do you want me to revert the dos/unix file endings change?

**Comment by dustinswales** [comment]
> > This all seems fine, except the change rte/mo_optical_props.F90. The changes should be isolated to the new "htmlinclude" for ty_optical_props_1scl/2str/nstr ccpp table properties.
> 
> Do you want me to revert the dos/unix file endings change?

Yes

**Comment by climbfuji** [comment]
> > > This all seems fine, except the change rte/mo_optical_props.F90. The changes should be isolated to the new "htmlinclude" for ty_optical_props_1scl/2str/nstr ccpp table properties.
> > 
> > 
> > Do you want me to revert the dos/unix file endings change?
> 
> Yes

Done.

**Review by dustinswales — APPROVED** [review]

**Pull request merged**
