### PR TITLE
fix to avoid overflow in minor gas code when using single precision, …

### PR DESCRIPTION
**Pull request by peterukk**
…plus faster find_gas using the findloc intrinsic

### CODE REVIEW

**Comment by peterukk** [comment]
Tests are failing with gfortran-8, because apparently this Fortran 2008 feature is only supported since gfortran 9.0

**Comment by RobertPincus** [comment]
@peterukk The CI tests are also failing with PGI compilers on Piz Daint. Perhaps it's better to remove the `findloc()` optimization and just retain the precision-preserving refactoring?

**Comment by peterukk** [comment]
Sure. The find_gas function accounted for 2.5% of RRTMGP's runtime with a block size of 18, and 4.9% with a block size of 10, so it's not super important. For just implementing the single precision fix, is that something you can from this pull request or should I make another one?

**Comment by peterukk** [comment]
Oops, there was a typo in the gas optics code. I'll just make a new pull request, its cleaner.

**Pull request closed without merging**
