### PR TITLE
RP dev

### PR DESCRIPTION
**Pull request by pernak18**
quick commit to address #103

### CODE REVIEW

**Comment by RobertPincus** [comment]
@pernak18 Can you please change the target of this PR from `master` to `develop`?

**Comment by pernak18** [comment]
@RobertPincus done. sorry -- i misunderstood the original directions.

**Comment by RobertPincus** [comment]
Hi @pernak18 So the CI is failing because the encoding of the variables differs between LW and SW. In the LW they are `char` but in the SW they are `strings` which I guess is how xarray writes them. 

```
[Mini-Me-2:~/Codes/rte-rrtmgp] robert% ncdump -h rrtmgp/data/rrtmgp-data-lw-g256-2018-12-04.nc | grep string_len
	string_len = 32 ;
	char gas_minor(minor_absorber, string_len) ;
	char gas_names(absorber, string_len) ;
	char identifier_minor(minor_absorber, string_len) ;
	char minor_gases_lower(minor_absorber_intervals_lower, string_len) ;
	char minor_gases_upper(minor_absorber_intervals_upper, string_len) ;
	char scaling_gas_lower(minor_absorber_intervals_lower, string_len) ;
	char scaling_gas_upper(minor_absorber_intervals_upper, string_len) ;
[Mini-Me-2:~/Codes/rte-rrtmgp] robert% ncdump -h rrtmgp/data/rrtmgp-data-sw-g224-2018-12-04.nc | grep string_len
	string_len = 32 ;
	string gas_minor(minor_absorber, string_len) ;
	string gas_names(absorber, string_len) ;
	string identifier_minor(minor_absorber, string_len) ;
	string minor_gases_lower(minor_absorber_intervals_lower, string_len) ;
	string minor_gases_upper(minor_absorber_intervals_upper, string_len) ;
	string scaling_gas_lower(minor_absorber_intervals_lower, string_len) ;
	string scaling_gas_upper(minor_absorber_intervals_upper, string_len) ;
```

**Comment by RobertPincus** [comment]
I think we should provide files that are in every way except data identical in the LW and the SW

**Comment by pernak18** [comment]
damnit. yes, my intent was identical LW and SW. the link i provided in the issue does warn against this behavior, and i didn't double check the array type. i was so focused on `string_len` and this phantom `string1` that `xarray.Dataset.to_netcdf` kept putting in for character arrays. i'll look into it more when i have some time

**Comment by RobertPincus** [comment]
@pernak18 Thanks for making any progress at all, I'm grateful. I used a lower level (`netCDF4`) interface some years ago - maybe there's something helpful here? https://github.com/RobertPincus/RFMIP-IRF-Scripts/blob/master/generate-output-file-templates.py

**Comment by pernak18** [comment]
@RobertPincus how about now?

**Comment by RobertPincus** [comment]
Thanks kindly, @pernak18. This looks great. Can you address the file format issue in #103 in this same PR?

**Comment by pernak18** [comment]
@RobertPincus how about now

**Pull request merged**
