### PR TITLE
Cray compiler supports nowadays no_create

### PR DESCRIPTION
**Pull request by jussienko**
Additional workarounds are still needed for getting the code to run with Cray compiler. However, this actually fixes issues in the code, so it might be nice to get this into the main code.

### CODE REVIEW

**Comment by RobertPincus** [comment]
@vectorflux @fomics These fixes were originally yours, I believe. Any objections to the changes?

**Review by vectorflux — CHANGES_REQUESTED** [review]
These #ifdefs were in for a good reason: CCE does not currently support NO_CREATE. Thus this code will not (yet) work on LUMI, and that is why they were put in in the first place. Do you have access to a HPE-CCE compiler which supports NO_CREATE?  I appears there is no runner for CCE-GPU-OpenACC.

**Comment by jussienko** [comment]
Since CCE 15.0.0 no_create is supported. The default CCE in LUMI is 15.0.0, and 15.0.1 is also available via normal module system.

The current `#ifdef`s do not actually even work as all the variables are not necessarily present (I guess that's why no_create's are used in the first place :-) ).

**Comment by vectorflux** [comment]
Good. We have the go ahead from Jussi, so these changes are fine.

**Pull request merged**
