### PR TITLE
Feature-numerics

### PR DESCRIPTION
**Pull request by RobertPincus**
This is mostly a first implementation of single precision (finally addressing #156)  following #39. The stand-alone tests are heavily revised - solutions to equivalent problems (e.g reversed vertical orientation) are tested with respect to numerical precision. Single precision fluxes differ from double precision in sample problems by as much as .13 W/m2.

### CODE REVIEW

**Comment by RobertPincus** [comment]
Note that @MennoVeerman's [comment](Menno’s concern? https://github.com/earth-system-radiation/rte-rrtmgp/pull/39#issuecomment-1044254604) is not addressed

**Comment by charleskawczynski** [comment]
Hi @RobertPincus, this looks great! I'm curious what sort of solution tolerance you're achieving with single precision. We're testing RRTMGP.jl with Float32, but the errors are quite large at the moment. cc @sriharshakandala

**Comment by RobertPincus** [comment]
@charleskawczynski Feel free to review the PR :-). 

In the test problems in our suite we see difference in single precision with respect to double precision of up to .13 W/m2. @peterukk has a different formulation for the minimum value of k that reduces errors further. I may implement that and/or other alternatives now that automated testing of single precision is in place.

**Review by Chiil — APPROVED** [review]
I have tested the code, and it produces good results. The implemented fixes make tests pass that fail with the `develop` code base.

**Pull request merged**
